config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :authors
  resources :books do
    resources :authorships, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships, dependent: :destroy
  has_many :books, through: :authorships
  validates :name, presence: true, uniqueness: true
  validates :birth_year, presence: true, numericality: { only_integer: true }
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: %i[show edit update destroy]
  def index
    #done
    @authors = Author.all
  end

  def show
    #done
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(authors_params)
    if @author.valid?
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def edit
    #done
  end

  def update
    #done
    @author.update(authors_params)
    if @author.valid?
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    #done
    @author.destroy
    redirect_to authors_path
  end

  private

  def find_author
    @author = Author.find(params[:id])
  end

  def authors_params
    params.require(:author).permit(:name, :birth_year)
  end
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  def create
    authorship = Authorship.create(author_id: params[:authorship][:author_id], book_id: params[:book_id])
    redirect_to book_path(authorship.book)
  end

  def destroy
    @authorship = Authorship.find(params[:book_id])
    @authorship.destroy
    redirect_to book_path(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  def index
    #done
    @books = Book.all
  end

  def show
    #done
    @authors = Author.all
    @authorship = Authorship.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(books_params)
    redirect_to books_path
  end

  def edit
    #done
  end

  def update
    #done
    @book.update(books_params)
    redirect_to @book
  end

  def destroy
    #done
    @book.destroy
    redirect_to books_path
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def books_params
    params.require(:book).permit(:title, :pages)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<% if @author.errors.any? %>
<div id="error_explanation">
  <ul>
  <% @author.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<ul style="list-style-type:none">
<%= form_for @author do |f| %>
<li><%= f.label :name %></li>
<li><%= f.text_field :name%></li>
<li><%= f.label :birth_year%></li>
<li><%= f.text_field :birth_year%></li>
<li><%= f.submit%></li>
<% end %>
</ul>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render 'form' %>

app/views/authors/index.html.erb
<h1>All Authors!</h1>
<%= link_to "New Author", new_author_path %>
<ul>
  <% @authors.each do |author| %>
  <li><%=link_to author.name, author%> <%=button_to "Delete #{author.name}", author, method: :delete%></li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<h1>Create New Author</h1>

<%= render 'form' %>

app/views/authors/show.html.erb
<h1><%=@author.name%>, (b. <%=@author.birth_year%>)</h1>
<h3>Books:</h3>
<ul>
  <% @author.books.each do |book| %>
  <li><%=link_to book.title, book%></li>
  <% end %>
</ul>
<%= link_to "Edit #{@author.name}", edit_author_path(@author) %>

app/views/books/index.html.erb
<h1>All Books!</h1>

<ul>
  <% @books.each do |book| %>
  <li><%=link_to book.title, book%></li>
  <% end %>
</ul>

app/views/books/show.html.erb
<h1><%=@book.title%>, (<%=@book.pages%> pages)</h1>
<h3>Authors:</h3>
<ul>
  <% @book.authorships.each do |authorship| %>
  <li><%=link_to authorship.author.name, authorship.author%><%=button_to "Delete #{authorship.author.name}", book_authorship_path(authorship), method: :delete%> </li>
  <% end %>
</ul>
<%= form_for [@book, @authorship] do |f| %>
<%= f.label :author_id %>
<%= f.collection_select :author_id, @authors, :id, :name %>
<%= f.submit "Add Author"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge2Mode2Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>